name: performance
description: Performance overlay package for Flutter apps that works on web.
version: 0.1.0+1
homepage: https://github.com/creativecreatorormaybenot/performance/tree/main/performance

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
