name: performance
description: Performance overlay package for Flutter apps that works on web.
version: 0.1.1
homepage: https://github.com/creativecreatorormaybenot/performance/tree/main/performance

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
