name: performance_example
description: Example app demonstrating use of the performance package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # We include the performance package in the example via path. In your regular
  # app, you will want to use a regular Pub dependency. See https://pub.dev/packages/performance/install
  # for details.
  performance:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
