name: performance_example
description: Example app demonstrating use of the performance package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # We include the performance package in the example via path. In your regular
  # app, you will want to use a regular Pub dependency.
  # See https://pub.dev/packages/performance/install for details.
  performance:
    path: ../

  funvas: ^0.1.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
