name: checks

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    timeout-minutes: 7
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} analysis on ${{ matrix.channel }}
    strategy:
      matrix:
        channel:
          - 'stable'
          - 'beta'
        package:
          - 'performance'
      fail-fast: false
    env:
      working-directory: ${{ matrix.package }}

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
      - name: pub get
        run: flutter pub get
        working-directory: ${{ env.working-directory }}
      - name: dart format
        run: dart format . --set-exit-if-changed
        working-directory: ${{ env.working-directory }}
      - run: flutter analyze
        working-directory: ${{ env.working-directory }}

  test:
    timeout-minutes: 11
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} testing on ${{ matrix.channel }}
    strategy:
      matrix:
        channel:
          - 'stable'
          - 'beta'
        package:
          - 'performance'
      fail-fast: false
    env:
      working-directory: ${{ matrix.package }}

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
      - run: flutter pub get
        working-directory: ${{ env.working-directory }}
      - run: flutter test
        working-directory: ${{ env.working-directory }}
