name: demo

on:
  push:
    branches:
      - main
    paths:
      - 'performance/lib/**'
      - 'performance/pubspec.yaml'
      - 'performance/example/pubspec.yaml'
      - 'performance/example/lib/**'
      - 'performance/example/web/**'
      - '.github/workflows/hosting.yml'

jobs:
  deploy:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    name: deployment

    steps:
      - uses: actions/checkout@v2.3.5
        with:
          persist-credentials: false
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build demo web app
        run: |
          cd performance/example
          flutter pub get
          flutter build web
          cd build/web
          touch ".nojekyll"
          echo "performance.creativemaybeno.dev" > CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: performance/example/build/web
          git-config-name: creativecreatorormaybenot
          git-config-email: creativecreatorormaybenot@gmail.com
          commit-message: Deploy demo app
